version: '3.9'

services:
  frontend:
    build: .
    container_name: runpath_frontend
    env_file:
      - .env
    networks:
      - frontend_net
      - orchestration_net

networks:
  frontend_net:
    external: true
  orchestration_net:
    external: true
